CRUD Author
Josephxrex/salle-arround-me-back-end pull request #3
Opened 2023-11-03 21:12 UTC by MarcosUvr

2023-11-03 21:22 UTC, EfrainJC commented on app/routes/author.py
> +            }
Verifica que en la respuesta respete esta estructura  y no la de la imagen.

![image](https://github.com/Josephxrex/salle-around-me-back-end/assets/140644589/7b9bc38b-ae75-4c34-a690-afeb5c601a27)

2023-11-03 21:23 UTC, EfrainJC commented on app/routes/author.py
> +                    "birthday": author.birthday,
Lo mismo con este end-point

2023-11-03 21:30 UTC, EfrainJC requested changes
First Review1

2023-11-10 21:21 UTC, danielperez1234 approved these changes

2023-11-10 23:04 UTC, EfrainJC approved these changes

2023-11-10 23:05 UTC, merged