Crud of city, mac address, material and tecnique
Josephxrex/salle-arround-me-back-end pull request #5
Opened 2023-11-03 21:55 UTC by artlunaa

city
mac_address
material
tecnique

By Emiliano Calzada and Arturo Luna

2023-11-03 22:24 UTC, EfrainJC commented on app/models/mac_address.py
> +class MacAddress(db.Model):
verifica como esta estructurada la tabla en la base de datos, mac_address

2023-11-03 22:48 UTC, EfrainJC requested changes
Revisen nuevamente el flujo de mac_address por que ahí había error , agregen el middleware en las rutas para proteger los end-points.

ejemplo:
Solo añadir un import 

`from middleware.middleware import jwt_required
@user_bp.route('/', methods=['POST'])
@jwt_required
`

2023-11-07 01:14 UTC, artlunaa commented on app/models/mac_address.py
> +class MacAddress(db.Model):
Te refieres al nombre en lower case? si es así, ya lo cambié, nada más la primera letra en mayúscula por convención al ser un modelo.

2023-11-07 01:29 UTC, EfrainJC commented on app/models/mac_address.py
> +class MacAddress(db.Model):
no importa mucho los las mayúsculas y minúsculas pero de presencia tienen que estar igual que el modelo ahí el error que da error es por el "_" que no tiene.

2023-11-08 20:05 UTC, EfrainJC approved these changes
Nice!

2023-11-08 20:26 UTC, merged